# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#       - SEARXNG_URL=${SEARXNG_URL}
#       - OPENAI_REALTIME_MODEL=${OPENAI_REALTIME_MODEL:-gpt-4o-realtime-preview-2024-12-17}
#       - NODE_ENV=development
#       - PORT=3000
#     volumes:
#       # Mount the entire codebase for hot reloading
#       - ./:/app
#       # Exclude node_modules from volume mounting to use container's modules
#       - /app/node_modules
#     restart: unless-stopped 

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SEARXNG_URL=${SEARXNG_URL}
      - OPENAI_REALTIME_MODEL=${OPENAI_REALTIME_MODEL:-gpt-4o-realtime-preview-2024-12-17}
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  # Caddy reverse proxy
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
